---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-start-application
  labels:
    app: quick-start-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quick-start-application
  template:
    metadata:
      labels:
        app: quick-start-application
    spec:
      serviceAccountName: quick-start-application
      containers:
      - name: quick-start-application
        # When running the pet-store, the following environment variables are expected:
        # DB_URL Url or connection string.
        # DB_USERNAME Username to connect as (not required for secretless).
        # DB_PASSWORD Password to connect as (not required for secretless).
        # https://github.com/conjurdemos/pet-store-demo
        image: cyberark/demo-app:latest
        imagePullPolicy: Always
        # By default, the embedded spring-boot server starts on port 8080
        ports:  
        - containerPort: 8080
        env:
        - name: DB_URL
          value: postgresql://localhost:5432/quick_start_db?sslmode=disable
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
      - name: secretless
        image: cyberark/secretless-broker:latest
        imagePullPolicy: Always
        args: ["-f", "/etc/secretless/secretless.yml"]
        volumeMounts:
        - name: config
          mountPath: /etc/secretless
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: quick-start-application-secretless-config

---
kind: Service
apiVersion: v1
metadata:
  name: quick-start-application
spec:
  selector:
    app: quick-start-application
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
