#!/bin/bash -e

./stop

# Generic utilities
. ./utils.sh

# Generic variables about the environment
. ./app_constants.sh

# Secrets known only by the security admin exported as env variables
. ./security_admin_secrets.sh


##################################################
step "Create a new namespace"

kubectl create namespace "${BACKEND_NAMESPACE}"

##################################################
step "Add certificates to Kubernetes Secrets"

# add pg certificates to kubernetes secrets
kubectl --namespace "${BACKEND_NAMESPACE}" \
  create secret generic \
  quick-start-backend-certs \
  --from-file "etc/pg_server.crt" \
  --from-file "etc/pg_server.key"

##################################################
step "Create StatefulSet for Database"

# POSTGRES_USER
# This optional environment variable is used in conjunction with POSTGRES_PASSWORD to set a user 
# and its password. This variable will create the specified user with superuser power and a database 
# with the same name. If it is not specified, then the default user of postgres will be used.

kubectl --namespace "${BACKEND_NAMESPACE}" apply \
  --filename "etc/pg.yml"

wait_for_app "quick-start-backend" "${BACKEND_NAMESPACE}"

##################################################
step "Create Application Database"

# Note: the `psql` command requires the --stdin flag
kubectl --namespace "${BACKEND_NAMESPACE}" \
  exec --stdin "$(first_pod quick-start-backend "${BACKEND_NAMESPACE}")" \
  -- \
    psql --username "${DB_ADMIN_USER}" \
    --command "CREATE DATABASE quick_start_db;"

##################################################
step "Create Database Table and Permissions"

db_url="quick-start-backend.${BACKEND_NAMESPACE}.svc.cluster.local:5432"

echo "Using DB endpoint: $db_url"

# a new pod by name postgres-cli is created
# Run commands in a pod and immediately remove it:
# To test a service from a temp pod inside cluster:
# k run temp --image=curlimages/curl -i --rm --restart=Never -- curl <svc name>
# after the command is run by the above pod, temp pod is deleted. Because of "--rm" 
# since the pod is stopped by "--restart=Never" 
# The DB is created in the StatefulSet "quick-start-backend", referenced in the "URL" below.

# EOSQL is a limit string for a block. The limit string signifies the start 
# and end of a text block to the bash interpreter (or any POSIXy shell). The limit string can 
# be any text that doesn't appear in your block, EOF is common in examples.
kubectl run --rm -i \
 --env PGPASSWORD="${DB_ADMIN_PASSWORD}" \
 --namespace "${BACKEND_NAMESPACE}" \
 --wait \
 postgres-cli \
 --image="postgres:9.6" -- \
    psql \
    --username "${DB_ADMIN_USER}" \
    "postgres://$db_url" \
    <<EOSQL
/* Create Application User */
CREATE USER ${DB_USER} PASSWORD '${DB_INITIAL_PASSWORD}';

/* Create Table */
CREATE TABLE pets (
    id serial primary key,
    name varchar(256)
);

/* Grant Permissions */
GRANT SELECT, INSERT ON public.pets TO ${DB_USER};
GRANT USAGE, SELECT ON SEQUENCE public.pets_id_seq TO ${DB_USER};
EOSQL

##################################################
step "Store DB credentials in Kubernetes Secrets"

# Note: We're creating a separate namespace for the app just to emphasize the
# conceptual separation between the duties of the security admin and the app
# developer
kubectl create namespace "${APP_NAMESPACE}"

# Store the credentials
kubectl --namespace "${APP_NAMESPACE}" \
  create secret generic "quick-start-backend-credentials" \
  --from-literal address="${db_url}" \
  --from-literal username="${DB_USER}" \
  --from-literal password="${DB_INITIAL_PASSWORD}"

# Usage of "--from-literal"
# https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/
##################################################
step "Create Application Service Account"

# create application service account
kubectl --namespace "${APP_NAMESPACE}" \
  create serviceaccount "quick-start-application"

# grant "quick-start-application" service account in
# "quick-start-application-ns" namespace access to
# "quick-start-backend-credentials"
kubectl --namespace "${APP_NAMESPACE}" \
  create --filename "etc/quick-start-application-entitlements.yml"

##################################################
step "Create and Store Secretless Configuration"

kubectl --namespace "${APP_NAMESPACE}" \
  create configmap "quick-start-application-secretless-config" \
  --from-file "etc/secretless.yml"
